In [1]:
## import necessary libraries
import pandas as pd
import numpy as np

In [2]:
## Importing the dataset
messages= pd.read_csv(r"C:\Users\pulki\Smart SMS Spam Detector\data\spam.csv", encoding= 'Latin-1')
messages.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
# Modifying the dataset
messages= messages[['v1', 'v2']]
messages.columns= ['label', 'message']
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
messages['message'].iloc[354]

'&lt;#&gt; ISH MINUTES WAS 5 MINUTES AGO. WTF.'

In [5]:
# Data Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pulki/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [6]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [7]:
# Text Preprocessing
# (remove symbols, lowercase, stemming, stopwords)
corpus= []
for i in range(0, len(messages)):
    review= re.sub('[^a-zA-Z]', " ", messages['message'][i])
    review= review.lower()
    review= review.split()
    review= [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review= " ".join(review)
    corpus.append(review)

In [8]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [9]:
# Feature Extraction - CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features= 5000)
X= cv.fit_transform(corpus).toarray()

In [10]:
# Label Encoding
y= pd.get_dummies(messages['label'])
y= y.iloc[:, 1].values
y

array([False, False,  True, ..., False, False, False], shape=(5572,))

In [11]:
# Train-Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.2, random_state= 12)

In [12]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model= MultinomialNB().fit(X_train, y_train)

In [13]:
# Prediction
y_pred= spam_detect_model.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, y_pred)

0.97847533632287

In [15]:
confusion_matrix(y_test, y_pred)

array([[951,  14],
       [ 10, 140]])

In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.99      0.99      0.99       965
        True       0.91      0.93      0.92       150

    accuracy                           0.98      1115
   macro avg       0.95      0.96      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [17]:
# Creating the TF-IDF Model
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf= TfidfVectorizer(max_features= 5000)
X1= tfidf.fit_transform(corpus).toarray()

In [18]:
y1= pd.get_dummies(messages['label'])
y1= y1.iloc[:, 1].values

In [19]:
# Train-Test Split
from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test= train_test_split(X1, y1, test_size= 0.2, random_state= 12)

In [20]:
spam_detect_model_1= MultinomialNB().fit(X1_train, y1_train)

In [21]:
# Prediction
y1_pred= spam_detect_model_1.predict(X1_test)

In [22]:
accuracy_score(y1_test, y1_pred)

0.9623318385650225

In [23]:
confusion_matrix(y1_test, y1_pred)

array([[964,   1],
       [ 41, 109]])

In [24]:
print(classification_report(y1_test, y1_pred))

              precision    recall  f1-score   support

       False       0.96      1.00      0.98       965
        True       0.99      0.73      0.84       150

    accuracy                           0.96      1115
   macro avg       0.98      0.86      0.91      1115
weighted avg       0.96      0.96      0.96      1115



# Word2vec Implementation

In [25]:
pip install gensim

Note: you may need to restart the kernel to use updated packages.


In [26]:
import gensim.downloader as api
wv_model= api.load('word2vec-google-news-300')
vec_king= wv_model['king']

In [27]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [28]:
from nltk.stem import WordNetLemmatizer
lemmatizer= WordNetLemmatizer()

In [29]:
corpus= []
for i in range(0, len(messages)):
    review= re.sub('[^a-zA-Z]', " ", messages['message'][i])
    review= review.lower()
    review= review.split()
    review= [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review= " ".join(review)
    corpus.append(review)

In [30]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

In [31]:
words= []
for sent in corpus:
    sents= sent_tokenize(sent)
    for s in sents:
        words.append(simple_preprocess(s))

In [32]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  'receivea',
 

In [33]:
import gensim

In [34]:
model= gensim.models.Word2Vec(words, window= 5, min_count= 2)

In [35]:
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'lt',
 'go',
 'ok',
 'day',
 'free',
 'know',
 'come',
 'like',
 'time',
 'good',
 'got',
 'text',
 'love',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'going',
 'home',
 'stop',
 'lor',
 'sorry',
 'see',
 'mobile',
 'still',
 'take',
 'back',
 'da',
 'reply',
 'think',
 'tell',
 'dont',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'pls',
 'please',
 'co',
 'msg',
 'min',
 'dear',
 'make',
 'night',
 'message',
 'well',
 'say',
 'thing',
 'much',
 'claim',
 'great',
 'hope',
 'oh',
 'hey',
 'number',
 'happy',
 'friend',
 'wat',
 'give',
 'work',
 'way',
 'yes',
 'www',
 'let',
 'prize',
 'right',
 'tomorrow',
 'already',
 'tone',
 'ask',
 'said',
 'cash',
 'win',
 'yeah',
 'amp',
 'really',
 'life',
 'im',
 'babe',
 'meet',
 'find',
 'morning',
 'last',
 'service',
 'year',
 'uk',
 'thanks',
 'miss',
 'would',
 'com',
 'also',
 'nokia',
 'anything',
 'lol',
 'care',
 'every',
 'feel',
 'keep',
 'pick',
 'sure',
 'sent',
 'contact',
 'urgent',


In [36]:
model.corpus_count

5564

In [37]:
model.epochs

5

In [38]:
model.wv.similar_by_word('kid')

[('without', 0.9974127411842346),
 ('hope', 0.9973983764648438),
 ('got', 0.9973933100700378),
 ('hello', 0.9973896145820618),
 ('never', 0.9973735809326172),
 ('said', 0.9973721504211426),
 ('one', 0.9973567128181458),
 ('happy', 0.9973512887954712),
 ('make', 0.9973505139350891),
 ('tell', 0.9973247051239014)]

In [39]:
model.wv['kid'].shape

(100,)

In [40]:
def avg_word2vec(doc):
    vectors=  [model.wv[word] for word in doc.split() if word in model.wv]
    if len(vectors) == 0:
        return np.zeros(model.vector_size)
    return np.mean(vectors, axis= 0)

In [41]:
pip install tqdm

Note: you may need to restart the kernel to use updated packages.


In [42]:
from tqdm import tqdm

In [43]:
words[73]

['performed']

In [44]:
type(model.wv.index_to_key)

list

In [45]:
# apply for the entire sentences
X= []
for i in range(len(words)):
    X.append(avg_word2vec(corpus[i]))

In [46]:
print(X[0])

[-1.21649466e-01  2.88603157e-01  7.29116052e-02 -3.98469977e-02
  4.86049652e-02 -3.49023849e-01  6.37974963e-02  5.35310030e-01
 -1.24745809e-01 -1.08658053e-01 -1.22409515e-01 -3.95059615e-01
 -6.44304454e-02  9.81924236e-02  3.35504971e-02 -2.33921751e-01
 -3.42419334e-02 -3.36813807e-01  1.17307780e-02 -4.82367486e-01
  5.62478863e-02  1.02357052e-01  3.55338827e-02 -8.60733688e-02
 -6.99316338e-02  1.18656615e-02 -2.52185732e-01 -2.08664015e-01
 -1.87893271e-01  6.33481145e-03  2.78611124e-01  1.09324276e-01
  1.57131944e-02 -1.05386548e-01 -1.07603192e-01  3.06794971e-01
  3.98435779e-02 -2.12623835e-01 -1.16563469e-01 -4.81822133e-01
 -1.83935033e-03 -2.18671456e-01 -2.20662933e-02  8.21892247e-02
  2.61904359e-01 -3.86229120e-02 -1.54265016e-01  5.78043656e-03
  1.83553472e-01  1.45930633e-01  1.48652077e-01 -2.17912510e-01
  2.21883249e-03  2.73957849e-05 -2.13357791e-01  1.82192370e-01
  2.14634344e-01  9.16751102e-03 -2.86492020e-01  8.37872550e-03
  7.68862888e-02  1.20610

In [47]:
len(X)

5564

In [48]:
type(X)

list

In [49]:
X_new= np.array(X)

In [50]:
X_new[3]

array([-1.55066609e-01,  3.58466119e-01,  9.52686295e-02, -4.97979410e-02,
        6.24222010e-02, -4.46506649e-01,  8.10790360e-02,  6.79384232e-01,
       -1.54463544e-01, -1.33978024e-01, -1.59513697e-01, -4.98290300e-01,
       -8.23925734e-02,  1.28511861e-01,  4.70589399e-02, -2.94157594e-01,
       -4.63076197e-02, -4.32941318e-01,  6.85228640e-03, -6.10062540e-01,
        6.94454834e-02,  1.31993592e-01,  4.72036712e-02, -1.08839042e-01,
       -8.47582445e-02,  1.77886728e-02, -3.24086279e-01, -2.57837087e-01,
       -2.37531230e-01,  8.73007532e-03,  3.55272770e-01,  1.39344916e-01,
        2.61680353e-02, -1.32017598e-01, -1.39317274e-01,  3.92428786e-01,
        4.99477349e-02, -2.65424341e-01, -1.47035345e-01, -6.07745409e-01,
        1.13838899e-03, -2.73249030e-01, -2.82656997e-02,  1.01009242e-01,
        3.32614243e-01, -4.90668155e-02, -1.93156540e-01,  1.02159968e-02,
        2.40385696e-01,  1.85926482e-01,  1.83943227e-01, -2.71656603e-01,
       -4.88402962e-04,  

In [51]:
X_new.shape

(5564, 100)